name: CI/CD workflow

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
      
      - name: Install Deps
        run: npm install
      
      - name: Run build
        run: npm run build

      - name: Run Tests
        run: npm run test